name: Test Android build

on:
  pull_request:
    paths:
      - 'package/android/**'
      - 'package/cpp/**'
      - 'example/package.json'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-11
    concurrency:
      group: android-example-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d

      - name: Set ANDROID_NDK
        run: echo "ANDROID_NDK=$ANDROID_HOME/ndk-bundle" >> $GITHUB_ENV

      - name: Install root node dependencies
        run: yarn

      - name: Download Skia Binary Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "build-skia.yml"
          repo: shopify/react-native-skia
          path: artifacts

      - name: Copy Artifacts to libs folder
        run: yarn workflow-copy-libs

      - name: Copy Skia Headers
        run: yarn copy-skia-headers
              
      - name: SDKs - accept licenses
        run: y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Package
        working-directory: package
        run: yarn install

      - name: Install example app node dependencies
        working-directory: example
        run: yarn

      - name: Cache hermes build
        uses: actions/cache@v3
        env:
          cache-name: cache-rn-hermes-engine
        with:
          path: example/node_modules/react-native
          key: ${{ runner.os }}-build-${{ env.cache-name }}-example-${{ hashFiles('**/react-native/package.json') }}

      - name: Cache android libraries
        uses: actions/cache@v3
        env:
          cache-name: cache-rn
        with:
          path: example/android/app/build/react-ndk
          key: ${{ runner.os }}-build-${{ env.cache-name }}-example-${{ hashFiles('**/react-native/package.json') }}
  
      - name: SKDs - download required images
        run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-30;default;x86_64"

      - name: Emulator - Create
        run: $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n Pixel_API_30 --device 'Nexus 5X' --package "system-images;android-30;default;x86_64" --sdcard 512M

      - name: Emulator - Boot
        run: $ANDROID_HOME/emulator/emulator -memory 4096 -avd Pixel_API_30 -wipe-data -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim &

      - name: ADB Wait For Device
        run: adb wait-for-any-device
        timeout-minutes: 3

      - name: Reverse TCP
        working-directory: example
        run: yarn android-reverse-tcp

      - name: Start Package Manager
        working-directory: example
        run: E2E=true yarn start &

      - name: Build App
        working-directory: example
        run: E2E=true yarn android

      - name: Run e2e Tests
        working-directory: package
        run: yarn e2e

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: package/src/__tests__/snapshots/
          name: Download-screenshots

