name: Test iOS build
on:
  pull_request:
    paths:
      - 'package/ios/**'
      - 'package/cpp/**'
      - 'example/package.json'
      - '.github/workflows/**'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        working-directory: [apps/paper] # app/fabric
    concurrency:
      group: ios-example-${{ matrix.working-directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore Pods from cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.working-directory }}/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/ios/Podfile.lock', matrix.working-directory)) }}

      - name: Install Pods
        working-directory: ${{ matrix.working-directory }}/ios
        run: pod install

      - name: Restore build artifacts from cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-ios-derived-data-${{ hashFiles(format('{0}/ios/Podfile.lock', matrix.working-directory)) }}
  
      - name: Build app
        working-directory: ${{ matrix.working-directory }}
        run: CI=true yarn ios --simulator 'iPhone 14 Pro'

      # - name: Run e2e tests
      #   working-directory: package
      #   run: yarn e2e

      # - name: Start package manager
      #   working-directory: example
      #   run: E2E=true yarn start &

      # - name: Take screenshot
      #   run: xcrun simctl io booted screenshot screenshot.png
        
      # - uses: actions/upload-artifact@v2
      #   with:
      #     path: screenshot.png
      #     name: Download-screenshots
