name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./
    concurrency:
      group: tests-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format-ios
        run: yarn clang-format-ios --dry-run --Werror

      - name: Run clang-format-android
        run: yarn clang-format-android --dry-run --Werror

      - name: Run clang-format-common
        run: yarn clang-format-common --dry-run --Werror

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install root node dependencies
        run: yarn install --frozen-lockfile

      - name: Typecheck the build scripts
        run: yarn tsc

      - name: Install Package
        run: cd package; yarn install --frozen-lockfile

      - name: Lint Package
        run: cd package; yarn lint;

      - name: TypeScript Package
        run: cd package; yarn tsc;

      - name: Run Package Unit tests
        run: cd package; yarn test;

      - name: Install Example
        run: cd example; yarn install --frozen-lockfile

      - name: Install Fabric Example
        run: cd fabricexample; yarn install --frozen-lockfile

      - name: Lint Example
        run: cd example; yarn lint;

      - name: TypeScript Example
        run: cd example; yarn tsc;

      - name: Run Example Unit tests
        run: cd example; yarn test;

      - name: Lint Fabric Example
        run: cd example; yarn lint;
  
      - name: TypeScript Fabric Example
        run: cd example; yarn tsc;
  
      - name: Run Fabric Example Unit tests
        run: cd example; yarn test;

      - name: Install Docs
        run: cd docs; yarn install --frozen-lockfile

      - name: TypeScript Example Docs
        run: cd docs; yarn build;
